version: '3.8'
services:
  devcontainer:
    platform: linux/x86_64

    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace:cached

    
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity